default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: quiz_appp_development
  pool: 5
  timeout: 5000
  encoding: unicode
  template: template0
  
test:
  adapter: postgresql
  database: quiz_appp_test
  pool: 5
  timeout: 5000
  encoding: unicode
  template: template0

production:
  adapter: postgresql
  database: quiz_appp_production
  pool: 5
  timeout: 5000
  encoding: unicode
  template: template0